# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0002_rezerwacja'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='do',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='od',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='pokoj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rezerwacje.Pokoj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='rodzina',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rezerwacje.Rodzina'),
            preserve_default=False,
        ),
    ]
