# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0003_auto_20170912_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('rodzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwacje.Rodzina')),
            ],
        ),
    ]
