# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0006_auto_20171123_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='rozmiar',
            field=models.IntegerField(null=True),
        ),
    ]
