# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0007_auto_20171123_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='limit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
