# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0008_rezerwacja_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='limit',
            field=models.NullBooleanField(),
        ),
    ]
