# Generated by Django 2.0 on 2018-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0009_auto_20171201_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodzina',
            name='nazwisko',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
